proyecto_unl:
  outputs:
    dev:
      dbname: db_warehouse
      host: postgres_warehouse
      password: password_dbt
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: user_dbt
  target: dev
taller_semana9:
  outputs:
    dev:
      dbname: db_warehouse
      host: postgres_warehouse
      password: password_dbt
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: user_dbt
  target: dev
